name: tcc3ds
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  brasil_fields: ^1.1.4
  sqflite: ^2.0.0+4
  path_provider: ^2.0.4
  validatorless: ^1.2.1
  shared_preferences: ^2.0.9
  get: ^4.3.8
  google_fonts: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo2.png
    - assets/MenuScreenSolidWall2.jpg
    - assets/emoji.png
    - assets/pedidoImagem.png